/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Clases.Clientes;
import Clases.Vendedores;
import Querys.ClienteQuerys;
import Querys.VendedorQuerys;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Marco
 */
public class VentanaPersonas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaPersonas
     */
    String persona;
    Boolean estado;
    public VentanaPersonas(String cadena) {
        initComponents();
        this.persona = cadena;
        tTitulo.setText("Ingreso de  " + cadena);
        lNombre.setText("Nombre del " +  cadena);
        lTelefono.setText("Telefono del " + cadena);
        lDPI.setText("DPI del " + cadena);
        lCorreo.setText("e-mail del " + cadena);
        lDireccion.setText("Direccion del " +cadena);
        bIngresar.setText("Ingresar " + cadena);
        setJTexFieldChanged(tNombre);
        this.estado = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTelefono = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        lDPI = new javax.swing.JLabel();
        tDPI = new javax.swing.JTextField();
        lCorreo = new javax.swing.JLabel();
        tCorreo = new javax.swing.JTextField();
        lDireccion = new javax.swing.JLabel();
        tDireccion = new javax.swing.JTextField();
        tTitulo = new javax.swing.JLabel();
        bIngresar = new javax.swing.JButton();
        lNombre = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        lTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lTelefono.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lTelefono.setText("Telefono");

        tTelefono.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        lDPI.setBackground(new java.awt.Color(255, 255, 255));
        lDPI.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lDPI.setText("DPI");

        tDPI.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        lCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lCorreo.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lCorreo.setText("e-mail");

        tCorreo.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        lDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lDireccion.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lDireccion.setText("Direccion");

        tDireccion.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        tTitulo.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tTitulo.setText("Ingreso");

        bIngresar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        lNombre.setBackground(new java.awt.Color(255, 255, 255));
        lNombre.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lNombre.setText("Nombre");

        tNombre.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTelefono)
                            .addComponent(lNombre)
                            .addComponent(lDPI)
                            .addComponent(lCorreo)
                            .addComponent(lDireccion))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNombre)
                            .addComponent(tTelefono)
                            .addComponent(tDPI)
                            .addComponent(tCorreo)
                            .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(tTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(bIngresar)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefono)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDPI)
                    .addComponent(tDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCorreo)
                    .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDireccion)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bIngresar)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed

        if(estado)
        {
            if(this.persona.equals("Vendedor"))
            {
                ingresarVendedor();
            }
            else
            {
                ingresarCliente();
            }
        }
        else
        {
            if(this.persona.equals("Vendedor"))
            {
                editarPersona(1);
            }
            else
            {
                editarPersona(1);
            }
        }
        limpiarT();
    }//GEN-LAST:event_bIngresarActionPerformed

    public void ingresarVendedor() {
        Vendedores vendedor = new Vendedores();
        vendedor.setCodigo("0");
        vendedor.setNombre(tNombre.getText());
        vendedor.setTelefono(tTelefono.getText());
        vendedor.setDpi(tDPI.getText());
        //vendedor.setCorreo(tCorreo.getText());
        vendedor.setDireccion(tDireccion.getText());
        VendedorQuerys.insertarVendedor(vendedor);
    }
    
    public void ingresarCliente() {
        Clientes cliente = new Clientes();
        cliente.setNombre(tNombre.getText());
        cliente.setTelefono(tTelefono.getText());
        cliente.setDpi(tDPI.getText());
        //cliente.setCorreo(tCorreo.getText());
        cliente.setDireccion(tDireccion.getText());
        ClienteQuerys.insertarCliente(cliente);        
    }
    
    public void editarPersona(int tipo) {
        if(tipo == 1)
        {
            Vendedores vendedor = new Vendedores();
            vendedor.setNombre(tNombre.getText());
            vendedor.setTelefono(tTelefono.getText());
            vendedor.setDpi(tDPI.getText());
            //vendedor.setCorreo(tCorreo.getText());
            vendedor.setDireccion(tDireccion.getText());
            VendedorQuerys.editarVendedor(vendedor);
        }
        else
        {
            Clientes cliente = new Clientes();
            cliente.setNombre(tNombre.getText());
            cliente.setTelefono(tTelefono.getText());
            cliente.setDpi(tDPI.getText());
            //vendedor.setCorreo(tCorreo.getText());
            cliente.setDireccion(tDireccion.getText());
            ClienteQuerys.editarClientes(cliente);
        }
        limpiarT();
        
    }
    
    public void limpiarT()
    {
        tCorreo.setText("");
        tDPI.setText("");
        tDireccion.setText("");
        tNombre.setText("");
        tTelefono.setText("");
    }
    
    private void actualizarDatosVendedor(Vendedores p)
    {
        //tCorreo.setText(p.getCorreo());
        tDPI.setText(p.getDpi());
        tDireccion.setText(p.getDireccion());
        tTelefono.setText(p.getTelefono());
        
    }
    
    private void actualizarDatosCliente(Clientes p)
    {
        //tCorreo.setText(p.getCorreo());
        tDPI.setText(p.getDpi());
        tDireccion.setText(p.getDireccion());
        tTelefono.setText(p.getTelefono());
        
    }
    
    private void setJTexFieldChanged(JTextField txt)
    {
        DocumentListener documentListener = new DocumentListener() {
 
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
        };
        txt.getDocument().addDocumentListener(documentListener);
 
    }
    
    private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            tCorreo.setText("");
            tDPI.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
 
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
            cambio();
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            cambio();
        }
    }
    
    private void cambio()
    {
        if(this.persona.equals("Vendedor"))
        {
            Vendedores p = VendedorQuerys.consultarVendedor(tNombre.getText());
            
            if(p!=null)
            {
                this.estado = false;
                bIngresar.setText("Editar " + persona);
                actualizarDatosVendedor(p);
            }
            else
            {
                this.estado = true;
                bIngresar.setText("Ingresar "+ persona);
                tCorreo.setText("");
            tDPI.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
            }
        }
        else
        {
            Clientes p = ClienteQuerys.consultarVendedor(tNombre.getText());
            
            if(p!=null)
            {
                this.estado = false;
                bIngresar.setText("Editar "+ persona);
                actualizarDatosCliente(p);
            }
            else
            {
                this.estado = true;
                bIngresar.setText("Ingresar " + persona);
                tCorreo.setText("");
            tDPI.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
            }
        }
        
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JLabel lDPI;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tDPI;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    private javax.swing.JLabel tTitulo;
    // End of variables declaration//GEN-END:variables
}
