/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaces;

import Clases.Personas;
import Querys.PersonaQuerys;
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.Icon;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Marco
 */
public class VentanaPersonas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaPersonas
     */
    String persona;
    Boolean estado;
    public VentanaPersonas(String cadena) {
        initComponents();
        this.persona = cadena;
        tTitulo.setText("Ingreso de  " + cadena);
        lNombre.setText("Nombre del " +  cadena);
        lTelefono.setText("Telefono del " + cadena);
        lDPI.setText("DPI del " + cadena);
        lCorreo.setText("e-mail del " + cadena);
        lDireccion.setText("Direccion del " +cadena);
        bIngresar.setText("Ingresar " + cadena);
        setJTexFieldChanged(tNombre);
        this.estado = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lTelefono = new javax.swing.JLabel();
        tTelefono = new javax.swing.JTextField();
        lDPI = new javax.swing.JLabel();
        tDPI = new javax.swing.JTextField();
        lCorreo = new javax.swing.JLabel();
        tCorreo = new javax.swing.JTextField();
        lDireccion = new javax.swing.JLabel();
        tDireccion = new javax.swing.JTextField();
        bIngresar = new javax.swing.JButton();
        lNombre = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(440, 40));

        tTitulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tTitulo.setForeground(new java.awt.Color(255, 255, 255));
        tTitulo.setText("Ingreso de Persona");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tTitulo)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tTitulo)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lTelefono.setText("Telefono");

        tTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tTelefono.setPreferredSize(new java.awt.Dimension(4, 30));

        lDPI.setBackground(new java.awt.Color(255, 255, 255));
        lDPI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lDPI.setText("DPI");

        tDPI.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tDPI.setPreferredSize(new java.awt.Dimension(4, 30));

        lCorreo.setBackground(new java.awt.Color(255, 255, 255));
        lCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lCorreo.setText("e-mail");

        tCorreo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tCorreo.setPreferredSize(new java.awt.Dimension(4, 30));

        lDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lDireccion.setText("Direccion");

        tDireccion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tDireccion.setPreferredSize(new java.awt.Dimension(4, 30));

        bIngresar.setBackground(new java.awt.Color(153, 0, 153));
        bIngresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        bIngresar.setForeground(new java.awt.Color(255, 255, 255));
        bIngresar.setText("Ingresar");
        bIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresarActionPerformed(evt);
            }
        });

        lNombre.setBackground(new java.awt.Color(255, 255, 255));
        lNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lNombre.setText("Nombre");

        tNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tNombre.setToolTipText("");
        tNombre.setPreferredSize(new java.awt.Dimension(4, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(281, Short.MAX_VALUE)
                .addComponent(bIngresar)
                .addGap(66, 66, 66))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTelefono)
                    .addComponent(lNombre)
                    .addComponent(lDPI)
                    .addComponent(lCorreo)
                    .addComponent(lDireccion))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tDPI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombre)
                    .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTelefono)
                    .addComponent(tTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDPI)
                    .addComponent(tDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCorreo)
                    .addComponent(tCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDireccion)
                    .addComponent(tDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bIngresar)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresarActionPerformed

        if(estado)
        {
            if(this.persona.equals("Vendedor"))
            {
                ingresarVendedor();
            }
            else
            {
                ingresarCliente();
            }
        }
        else
        {
            if(this.persona.equals("Vendedor"))
            {
                editarPersona(1);
            }
            else
            {
                editarPersona(1);
            }
        }
        limpiarT();
    }//GEN-LAST:event_bIngresarActionPerformed

    public void ingresarVendedor() {
        Personas persona = new Personas();
        persona.setNombre(tNombre.getText());
        persona.setTelefono(tTelefono.getText());
        persona.setDpi(tDPI.getText());
        persona.setCorreo(tCorreo.getText());
        persona.setDireccion(tDireccion.getText());
        persona.setIdTipoPersona(1);
        PersonaQuerys.insertarPersona(persona);
    }
    
    public void ingresarCliente() {
        Personas persona = new Personas();
        persona.setNombre(tNombre.getText());
        persona.setTelefono(tTelefono.getText());
        persona.setDpi(tDPI.getText());
        persona.setCorreo(tCorreo.getText());
        persona.setDireccion(tDireccion.getText());
        persona.setIdTipoPersona(2);
        PersonaQuerys.insertarPersona(persona);        
    }
    
    public void editarPersona(int tipo) {
        if(tipo == 1)
        {
            Personas persona = new Personas();
            persona.setNombre(tNombre.getText());
            persona.setTelefono(tTelefono.getText());
            persona.setDpi(tDPI.getText());
            persona.setCorreo(tCorreo.getText());
            persona.setDireccion(tDireccion.getText());
            persona.setIdTipoPersona(1);
            PersonaQuerys.editarPersona(persona);
        }
        else
        {
            Personas persona = new Personas();
            persona.setNombre(tNombre.getText());
            persona.setTelefono(tTelefono.getText());
            persona.setDpi(tDPI.getText());
            persona.setCorreo(tCorreo.getText());
            persona.setDireccion(tDireccion.getText());
            persona.setIdTipoPersona(2);
            PersonaQuerys.editarPersona(persona);
        }
        limpiarT();
        
    }
    
    public void limpiarT()
    {
        tCorreo.setText("");
        tDPI.setText("");
        tDireccion.setText("");
        tNombre.setText("");
        tTelefono.setText("");
    }
    
    private void actualizarDatosPersona(Personas p)
    {
        tCorreo.setText(p.getCorreo());
        tDPI.setText(p.getDpi());
        tDireccion.setText(p.getDireccion());
        tTelefono.setText(p.getTelefono());
        
    }
    
    private void setJTexFieldChanged(JTextField txt)
    {
        DocumentListener documentListener = new DocumentListener() {
 
        @Override
        public void changedUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void insertUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
 
        @Override
        public void removeUpdate(DocumentEvent documentEvent) {
            printIt(documentEvent);
        }
        };
        txt.getDocument().addDocumentListener(documentListener);
 
    }
    
    private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();
 
        if (type.equals(DocumentEvent.EventType.CHANGE))
        {
            tCorreo.setText("");
            tDPI.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
 
        }
        else if (type.equals(DocumentEvent.EventType.INSERT))
        {
            cambio();
        }
        else if (type.equals(DocumentEvent.EventType.REMOVE))
        {
            cambio();
        }
    }
    
    private void cambio()
    {
        if(this.persona.equals("Vendedor"))
        {
            Personas p = PersonaQuerys.consultarPersona(tNombre.getText(), "1");
            
            if(p!=null)
            {
                this.estado = false;
                bIngresar.setText("Editar " + persona);
                actualizarDatosPersona(p);
            }
            else
            {
                this.estado = true;
                bIngresar.setText("Ingresar "+ persona);
                tCorreo.setText("");
            tDPI.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
            }
        }
        else
        {
            Personas p = PersonaQuerys.consultarPersona(tNombre.getText(), "2");
            
            if(p!=null)
            {
                this.estado = false;
                bIngresar.setText("Editar "+ persona);
                actualizarDatosPersona(p);
            }
            else
            {
                this.estado = true;
                bIngresar.setText("Ingresar " + persona);
                tCorreo.setText("");
            tDPI.setText("");
            tDireccion.setText("");
            tTelefono.setText("");
            }
        }
        
    }    
    
    
    public void setIcon(Icon anIcon){
        setFrameIcon(anIcon);
    }
     
    @Override
    protected void paintComponent(Graphics g) {
        g.setColor(new Color(100, 0, 4, 85));
        g.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bIngresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lCorreo;
    private javax.swing.JLabel lDPI;
    private javax.swing.JLabel lDireccion;
    private javax.swing.JLabel lNombre;
    private javax.swing.JLabel lTelefono;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tDPI;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    private javax.swing.JLabel tTitulo;
    // End of variables declaration//GEN-END:variables
}
