/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package xocolata_v2;
import java.awt.BorderLayout;
import java.awt.Container;
import java.io.File;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Rosario
 */
public class Rinventario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Rinventario
     * @param parametroBusqueda
     * @param rutaReporte
     */
    public Rinventario(String parametroBusqueda, String rutaReporte) {
        initComponents();
        initComponents();
        this.closable = true;
        this.maximizable = true;
        this.resizable = true;
        this.iconable = true;
        setBounds(0, 0, 900, 600);
        com.mysql.jdbc.Connection conect=(com.mysql.jdbc.Connection) ConexionDB.ObtenerConexion();
        
        if(conect!=null){
            System.out.println("Conexion correcta");
        }
        String archivo = rutaReporte;
         try
         {
            File xocolata =   new File("src\\Imagenes\\xocolata.png");
            
            Map parametro = new HashMap();
            parametro.put("dato", parametroBusqueda);
            parametro.put("xocolata", xocolata);
                          
             JasperReport jasperReport= (JasperReport) JRLoader.loadObject(archivo);
             JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parametro, conect);  // conect 
             net.sf.jasperreports.view.JRViewer view = new net.sf.jasperreports.view.JRViewer(jasperPrint);
             Container c = getContentPane();
             c.setLayout(new BorderLayout());
             c.add(view);
        } catch (JRException ex) {
            System.out.println("Error " + ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

